---
- name: Copy Pentaho Data Integration (PDI)
  copy:
    src: 'tools/pdi-ce-8.2.0.0-342.zip'
    dest: '/opt/pentaho/'
    owner: pentaho
    group: pentaho
    mode: 0644

- name: Unarchive Pentaho Data Integration
  unarchive:
    copy: no
    src: /opt/pentaho/pdi-ce-8.2.0.0-342.zip
    dest: /opt/pentaho
    creates: /opt/pentaho/data-integration/spoon.sh

- name: Remove Pentaho Data Integration zip file
  file:
    state: absent
    path: "/opt/pentaho/pdi-ce-8.2.0.0-342.zip"

- name: Set pentaho user as owner
  file: path=/opt/pentaho state=directory owner=pentaho group=pentaho recurse=yes
