---
- name: create pentaho Unix's user
  user: name=pentaho state=present

- name: create directory to copy pentaho and related tools
  file: path=/opt/pentaho state=directory owner=pentaho group=pentaho

- name: copy SQL Power Architect v1.8
  copy:
    src: 'SQL-Power-Architect-generic-jdbc-1.0.8.tar.gz'
    dest: '/opt/pentaho/'
    owner: pentaho
    group: pentaho
    mode: 0644

# - name: download SQL Power Architect v1.0.8
#   when: not architect.stat.exists
#   get_url:
#     url: 'http://download.sqlpower.ca/architect/1.0.8/community/SQL-Power-Architect-generic-jdbc-1.0.8.tar.gz'
#     dest: /tmp/SQL-Power-Architect-generic-jdbc-1.0.8.tar.gz
#     force: no
#     checksum: sha1:3419c12b21a3cc151359563921c220087a64f251

- name: unarchive SQL Power Architect v1.0.8
  unarchive:
    copy: no
    src: /opt/pentaho/SQL-Power-Architect-generic-jdbc-1.0.8.tar.gz
    dest: /opt/pentaho
    creates: /opt/pentaho/architect-1.0.8/architect.jar
