---
- name: Copy SQL Power Architect
  copy:
    src: 'tools/SQL-Power-Architect-generic-jdbc-1.0.8.tar.gz'
    dest: '/opt/tools/'
    owner: pentaho
    group: pentaho
    mode: 0644

- name: Unarchive SQL Power Architect
  unarchive:
    copy: no
    src: /opt/tools/SQL-Power-Architect-generic-jdbc-1.0.8.tar.gz
    dest: /opt/tools
    creates: /opt/tools/architect-1.0.8/architect.jar

- name: Remove default JDBC Driver
  file:
    state: absent
    path: "/opt/tools/architect-1.0.8/jdbc/postgresql-8.2-506.jdbc3.jar"

- name: Copy Uptaded JDBC Driver
  copy:
    src: 'jdbc/postgresql-42.2.6.jar'
    dest: '/opt/tools/architect-1.0.8/jdbc'
    owner: pentaho
    group: pentaho
    mode: 0644

- name: Remove SQL Power Architect zip file
  file:
    state: absent
    path: "/opt/tools/SQL-Power-Architect-generic-jdbc-1.0.8.tar.gz"
