---
- name: install PostgreSQL server database
  apt: name={{ item }}
  with_items:
    - postgresql
    - postgresql-contrib
    - pgadmin3

- name: set postgres password
  shell: apt-get update

# setting password for PostgreSQL database, user postgres
# sudo -u postgres psql postgres
# \password postgres
