---
- name: Copy DataCleaner
  copy:
    src: 'tools/DataCleaner-5.7.0.zip'
    dest: '/opt/tools/'
    owner: pentaho
    group: pentaho
    mode: 0644

- name: Unarchive DataCleaner
  unarchive:
    copy: no
    src: /opt/tools/DataCleaner-5.7.0.zip
    dest: /opt/tools
    creates: /opt/tools/DataCleaner/datacleaner.sh

- name: Remove DataCleaner zip file
  file:
    state: absent
    path: "/opt/tools/DataCleaner-5.7.0.zip"